# Generated by Django 4.0 on 2022-01-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variationcategory_options_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationcategory',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
