# Generated by Django 4.0 on 2022-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variationcategory_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationcategory',
            name='display',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
