# Generated by Django 4.0 on 2022-01-10 14:35

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variationcategory_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_image',
            field=models.ImageField(null=True, upload_to=store.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='variationcategory',
            name='display',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
