# Generated by Django 4.0 on 2022-01-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variation_variation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
