# Generated by Django 4.0 on 2022-01-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='province',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
