# Generated by Django 4.0 on 2022-01-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fullname',
        ),
    ]
