# Generated by Django 4.0 on 2022-01-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
